import React, { useEffect, useState, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft, Download } from 'lucide-react';
import api from '../api/axios';
import toast from 'react-hot-toast';

const PayslipView = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [payslip, setPayslip] = useState(null);
  const [loading, setLoading] = useState(true);
  const printRef = useRef();

  useEffect(() => {
    fetchPayslip();
  }, [id]);

  const fetchPayslip = async () => {
    try {
      setLoading(true);
      const res = await api.get(`/payslips/${id}`);
      setPayslip(res.data.data);
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to load payslip');
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '300px' }}>
        <div className="spinner" />
      </div>
    );
  }

  if (!payslip) {
    return (
      <div style={{ textAlign: 'center', padding: '40px' }}>
        <p style={{ color: 'var(--text-muted)' }}>Payslip not found.</p>
        <button className="btn btn-primary" onClick={() => navigate(-1)} style={{ marginTop: '16px' }}>
          Go Back
        </button>
      </div>
    );
  }

  const salary = payslip.salaryId || {};
  const employee = payslip.employeeId || {};

  // Format period string
  const periodStart = salary.payPeriodStart
    ? new Date(salary.payPeriodStart).toLocaleDateString('en-NP', { day: '2-digit', month: 'short', year: 'numeric' })
    : `01 ${payslip.monthName} ${payslip.year}`;
  const periodEnd = salary.payPeriodEnd
    ? new Date(salary.payPeriodEnd).toLocaleDateString('en-NP', { day: '2-digit', month: 'short', year: 'numeric' })
    : `30 ${payslip.monthName} ${payslip.year}`;

  const data = {
    payslipNumber: payslip.payslipNumber,
    monthYear: `${payslip.monthName} ${payslip.year}`,
    employeeName: employee.name || '—',
    panNumber: employee.panNumber || '—',
    designation: employee.designation || '—',
    period: `${periodStart} – ${periodEnd}`,
    monthlyBasic: salary.monthlyBasicSalary || 0,
    da: salary.dearnessAllowance || 0,
    ssfEmployer: salary.ssfEmployerContribution || 0,
    totalGross: salary.totalGrossPay || 0,
    ssfDeduction: salary.ssfEmployeeContribution || 0,
    cit: salary.citAmount || 0,
    tax: salary.taxAmount || 0,
    netPay: salary.netPay || 0,
    attendanceSummary: payslip.attendanceSummary || {},
    generatedBy: payslip.generatedBy?.name || 'Admin',
    generatedAt: payslip.generatedAt
      ? new Date(payslip.generatedAt).toLocaleDateString('en-NP')
      : new Date().toLocaleDateString('en-NP'),
  };

  return (
    <>
      {/* Screen: action bar (hidden during print) */}
      <div className="no-print" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
          <button className="btn btn-outline" onClick={() => navigate(-1)}>
            <ArrowLeft size={16} /> Back
          </button>
          <div>
            <h2 style={{ margin: 0 }}>Payslip #{data.payslipNumber}</h2>
            <small style={{ color: 'var(--text-muted)' }}>Generated by {data.generatedBy} · {data.generatedAt}</small>
          </div>
        </div>
        <button className="btn btn-primary" onClick={handlePrint}>
          <Download size={16} /> Download PDF
        </button>
      </div>

      {/* Card wrapper (screen only) */}
      <div className="card no-print" style={{ padding: '32px', display: 'flex', justifyContent: 'center', background: 'var(--bg-card)' }}>
        <PayslipTemplate data={data} />
      </div>

      <div className="card no-print payslip-attendance-summary">
        <h3>Attendance Used</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div><span className="text-secondary text-sm">Present</span><strong>{data.attendanceSummary.present || 0}</strong></div>
          <div><span className="text-secondary text-sm">Half Days</span><strong>{data.attendanceSummary.halfDay || 0}</strong></div>
          <div><span className="text-secondary text-sm">Leave / Absent</span><strong>{(data.attendanceSummary.leave || 0) + (data.attendanceSummary.absent || 0)}</strong></div>
          <div><span className="text-secondary text-sm">Total Hours</span><strong>{data.attendanceSummary.totalHours || 0}h</strong></div>
        </div>
      </div>

      {/* Print-only version (full page) */}
      <div className="print-only" style={{ display: 'none' }}>
        <PayslipTemplate data={data} />
      </div>
    </>
  );
};

const fmt = (num) =>
  Number(num).toLocaleString('en-NP', { minimumFractionDigits: 0, maximumFractionDigits: 2 });

const PayslipTemplate = ({ data }) => {
  const rowStyle = { display: 'flex', justifyContent: 'space-between', padding: '7px 0' };
  const boldRowStyle = { ...rowStyle, fontWeight: '700' };
  const dividerStyle = { borderTop: '1px solid #334155', margin: '8px 0' };
  const printDivider = { borderTop: '1px solid #000', margin: '8px 0' };

  return (
    <div className="payslip-box">
      {/* Header */}
      <div className="payslip-header">
        <img src="/logo.png" alt="Dzeno Tech Nepal" style={{ width: '220px', maxWidth: '100%', marginBottom: '10px' }} />
        <h2 style={{ margin: 0, fontSize: '22px', fontWeight: '700', letterSpacing: '0.5px' }}>
          Dzeno Tech Nepal
        </h2>
        <div style={{ fontSize: '14px', marginTop: '4px', opacity: 0.85 }}>Lalitpur, Nepal</div>
        <div className="payslip-divider" />
        <div style={{ fontSize: '15px', fontWeight: '600', letterSpacing: '1px', marginTop: '4px' }}>
          Payslip – {data.monthYear}
        </div>
      </div>

      {/* Employee info row */}
      <div className="payslip-info-grid">
        <div className="payslip-info-cell">
          <span className="payslip-label">Name</span>
          <span className="payslip-value">{data.employeeName}</span>
        </div>
        <div className="payslip-info-cell">
          <span className="payslip-label">PAN</span>
          <span className="payslip-value">{data.panNumber}</span>
        </div>
        <div className="payslip-info-cell">
          <span className="payslip-label">Designation</span>
          <span className="payslip-value">{data.designation}</span>
        </div>
        <div className="payslip-info-cell">
          <span className="payslip-label">Period</span>
          <span className="payslip-value">{data.period}</span>
        </div>
      </div>

      <div className="payslip-section-title">Attendance Summary</div>
      <div className="payslip-info-grid payslip-attendance-print-grid">
        <div className="payslip-info-cell"><span className="payslip-label">Present Days</span><span className="payslip-value">{data.attendanceSummary.present || 0}</span></div>
        <div className="payslip-info-cell"><span className="payslip-label">Half Days</span><span className="payslip-value">{data.attendanceSummary.halfDay || 0}</span></div>
        <div className="payslip-info-cell"><span className="payslip-label">Leave / Absent</span><span className="payslip-value">{(data.attendanceSummary.leave || 0) + (data.attendanceSummary.absent || 0)}</span></div>
        <div className="payslip-info-cell"><span className="payslip-label">Total Hours</span><span className="payslip-value">{data.attendanceSummary.totalHours || 0}h</span></div>
      </div>

      {/* Net Pay Calculation */}
      <div className="payslip-section-title">Net Pay Calculation</div>

      <div className="payslip-calc">
        {/* Header row */}
        <div style={{ ...boldRowStyle, borderBottom: '2px solid currentColor', paddingBottom: '8px', marginBottom: '4px' }}>
          <span>Particulars</span>
          <span>Amount (NPR)</span>
        </div>

        {/* Earnings */}
        <div style={rowStyle}>
          <span>Monthly Basic Salary</span>
          <span>{fmt(data.monthlyBasic)}</span>
        </div>
        <div style={rowStyle}>
          <span>Dearness Allowance</span>
          <span>{fmt(data.da)}</span>
        </div>
        <div style={rowStyle}>
          <span>SSF Employer Contribution (20%)</span>
          <span>{fmt(data.ssfEmployer)}</span>
        </div>

        <div style={dividerStyle} />

        {/* Gross */}
        <div style={boldRowStyle}>
          <span>Total Gross Pay</span>
          <span>{fmt(data.totalGross)}</span>
        </div>

        <div style={dividerStyle} />

        {/* Deductions */}
        <div style={rowStyle}>
          <span>Less: Contribution to SSF (31%)</span>
          <span style={{ color: '#ef4444' }}>({fmt(data.ssfDeduction)})</span>
        </div>
        <div style={rowStyle}>
          <span>Less: CIT Contribution</span>
          <span style={{ color: data.cit > 0 ? '#ef4444' : undefined }}>
            {data.cit > 0 ? `(${fmt(data.cit)})` : fmt(data.cit)}
          </span>
        </div>
        {data.tax > 0 && (
          <div style={rowStyle}>
            <span>Tax</span>
            <span style={{ color: '#ef4444' }}>({fmt(data.tax)})</span>
          </div>
        )}

        <div style={dividerStyle} />

        {/* Net Pay */}
        <div style={{ ...boldRowStyle, fontSize: '16px', color: '#22c55e' }}>
          <span>Net Pay transfer to bank</span>
          <span>{fmt(data.netPay)}</span>
        </div>

        <div style={dividerStyle} />
      </div>

      {/* Signature block */}
      <div className="payslip-signatures">
        <div>
          <div style={{ marginBottom: '32px' }}>Authorized Signature:</div>
          <div style={{ borderTop: '1px solid currentColor', width: '180px', paddingTop: '4px', fontSize: '12px' }}>
            Signature
          </div>
        </div>
        <div>
          <div style={{ marginBottom: '32px' }}>Company Seal:</div>
          <div style={{ border: '1px solid currentColor', width: '100px', height: '60px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '11px', opacity: 0.5 }}>
            [SEAL]
          </div>
        </div>
      </div>

      <div style={{ borderTop: '1px solid currentColor', marginTop: '16px', paddingTop: '10px', fontSize: '11px', opacity: 0.6, textAlign: 'center' }}>
        This is a computer-generated payslip. No physical signature is required.
        Payslip No: {data.payslipNumber}
      </div>
    </div>
  );
};

export default PayslipView;
