import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../api/axios';
import toast from 'react-hot-toast';

const Payslips = () => {
  const navigate = useNavigate();
  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPayslips = async () => {
      try {
        const res = await api.get('/payslips');
        setPayslips(res.data.data || []);
      } catch (err) {
        toast.error(err.response?.data?.message || 'Failed to load payslips');
      } finally {
        setLoading(false);
      }
    };

    fetchPayslips();
  }, []);

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h1>Payslips</h1>
      </div>

      <div className="card">
        <div className="table-container">
          <table className="table">
            <thead>
              <tr>
                <th>Payslip No.</th>
                <th>Employee</th>
                <th>Month/Year</th>
                <th>Net Pay</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan="7" className="text-center text-secondary">Loading payslips...</td>
                </tr>
              ) : payslips.length === 0 ? (
                <tr>
                  <td colSpan="7" className="text-center text-secondary">No payslips found.</td>
                </tr>
              ) : payslips.map(ps => (
                <tr key={ps._id}>
                  <td>{ps.payslipNumber}</td>
                  <td className="font-medium">{ps.employeeId?.name || '—'}</td>
                  <td>{ps.monthName} {ps.year}</td>
                  <td className="font-bold">NPR {Number(ps.salaryId?.netPay || 0).toLocaleString()}</td>
                  <td>{ps.generatedBy?.name || '—'}</td>
                  <td>{ps.generatedAt ? new Date(ps.generatedAt).toLocaleDateString('en-NP') : '—'}</td>
                  <td>
                    <button className="btn btn-outline text-xs" onClick={() => navigate(`/admin/payslips/${ps._id}`)}>
                      View & Print
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Payslips;
