import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { FilePlus } from "lucide-react";
import Modal from "../components/ui/Modal";
import api from "../api/axios";
import toast from "react-hot-toast";
import { useAuth } from "../hooks/useAuth";

const Payslips = () => {
  const navigate = useNavigate();
  const { user, hasRole } = useAuth();
  const isEmployeeView = hasRole(["developer", "employee", "intern"]);
  const [payslips, setPayslips] = useState([]);
  const [loading, setLoading] = useState(true);
  const [salaries, setSalaries] = useState([]);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [selectedSalaryId, setSelectedSalaryId] = useState("");
  const [generating, setGenerating] = useState(false);

  const fetchData = useCallback(async () => {
    try {
      const payslipRequest = isEmployeeView
        ? api.get(`/payslips/employee/${user?._id || user?.id}`)
        : api.get("/payslips");
      const requests = isEmployeeView ? [payslipRequest] : [payslipRequest, api.get("/salary")];
      const [payslipResponse, salaryResponse] = await Promise.all(requests);
      setPayslips(Array.isArray(payslipResponse.data.data) ? payslipResponse.data.data : []);
      setSalaries(Array.isArray(salaryResponse?.data?.data) ? salaryResponse.data.data : []);
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to load payslips");
    } finally {
      setLoading(false);
    }
  }, [isEmployeeView, user]);

  useEffect(() => {
    const timeoutId = window.setTimeout(() => {
      void fetchData();
    }, 0);

    return () => window.clearTimeout(timeoutId);
  }, [fetchData]);

  const generatePayslip = async (event) => {
    event.preventDefault();
    if (!selectedSalaryId) return;
    try {
      setGenerating(true);
      const response = await api.post("/payslips/generate", { salaryId: selectedSalaryId });
      toast.success("Payslip generated from salary and attendance records");
      setIsModalOpen(false);
      navigate(`/admin/payslips/${response.data.data._id}`);
    } catch (err) {
      toast.error(err.response?.data?.message || "Failed to generate payslip");
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h1>Payslips</h1>
      </div>
      {!isEmployeeView && (
        <button className="btn btn-primary" onClick={() => setIsModalOpen(true)}>
          <FilePlus size={16} /> Generate Payslip
        </button>
      )}

      <div className="card">
        <div className="table-container">
          <table className="table">
            <thead>
              <tr>
                <th>Payslip No.</th>
                {!isEmployeeView && <th>Employee</th>}
                <th>Month/Year</th>
                <th>Net Pay</th>
                {!isEmployeeView && <th>Generated By</th>}
                <th>Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={isEmployeeView ? 5 : 7} className="text-center text-secondary">
                    Loading payslips...
                  </td>
                </tr>
              ) : payslips.length === 0 ? (
                <tr>
                  <td colSpan={isEmployeeView ? 5 : 7} className="text-center text-secondary">
                    No payslips found.
                  </td>
                </tr>
              ) : (
                payslips.map((ps) => (
                  <tr key={ps._id}>
                    <td>{ps.payslipNumber}</td>
                    {!isEmployeeView && (
                      <td className="font-medium">{ps.employeeId?.name || "—"}</td>
                    )}
                    <td>
                      {ps.monthName} {ps.year}
                    </td>
                    <td className="font-bold">
                      NPR {Number(ps.salaryId?.netPay || 0).toLocaleString()}
                    </td>
                    {!isEmployeeView && <td>{ps.generatedBy?.name || "—"}</td>}
                    <td>
                      {ps.generatedAt ? new Date(ps.generatedAt).toLocaleDateString("en-NP") : "—"}
                    </td>
                    <td>
                      <button
                        className="btn btn-outline text-xs"
                        onClick={() => navigate(`/admin/payslips/${ps._id}`)}
                      >
                        View & Print
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {!isEmployeeView && (
        <Modal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} title="Generate Payslip">
          <form className="flex flex-col gap-4" onSubmit={generatePayslip}>
            <div className="form-group">
              <label className="form-label">Salary Record</label>
              <select
                className="select"
                value={selectedSalaryId}
                onChange={(event) => setSelectedSalaryId(event.target.value)}
                required
              >
                <option value="">Select salary record...</option>
                {salaries.map((salary) => (
                  <option key={salary._id} value={salary._id}>
                    {salary.employeeId?.name || "Employee"} - {salary.monthName} {salary.year} - NPR{" "}
                    {Number(salary.netPay || 0).toLocaleString("en-NP")}
                  </option>
                ))}
              </select>
            </div>
            <p className="text-secondary text-sm">
              The payslip will include the selected salary and attendance records for that employee
              and pay period.
            </p>
            <button type="submit" className="btn btn-primary w-full" disabled={generating}>
              {generating ? "Generating..." : "Generate Payslip"}
            </button>
          </form>
        </Modal>
      )}
    </div>
  );
}
export default Payslips;