import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import Badge from '../components/ui/Badge';

const Payslips = () => {
  const navigate = useNavigate();
  const [payslips] = useState([
    { id: '1', no: 'PS-2024-04-001', employeeName: 'Sujan Aryal', monthYear: 'April 2024', netPay: 32690, generatedBy: 'Admin', date: '2024-05-01' },
    { id: '2', no: 'PS-2024-03-001', employeeName: 'Sujan Aryal', monthYear: 'March 2024', netPay: 32690, generatedBy: 'Admin', date: '2024-04-01' },
  ]);

  return (
    <div>
      <div className="flex justify-between items-center mb-6">
        <h1>Payslips</h1>
      </div>

      <div className="card">
        <div className="table-container">
          <table className="table">
            <thead>
              <tr>
                <th>Payslip No.</th>
                <th>Employee</th>
                <th>Month/Year</th>
                <th>Net Pay</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {payslips.map(ps => (
                <tr key={ps.id}>
                  <td>{ps.no}</td>
                  <td className="font-medium">{ps.employeeName}</td>
                  <td>{ps.monthYear}</td>
                  <td className="font-bold">NPR {ps.netPay.toLocaleString()}</td>
                  <td>{ps.generatedBy}</td>
                  <td>{ps.date}</td>
                  <td>
                    <button className="btn btn-outline text-xs" onClick={() => navigate(`/admin/payslips/${ps.id}`)}>
                      View & Print
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Payslips;
